# -*- coding: utf-8 -*-
"""Python_Listas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZL0Lf_-C8dTmvZFXMIQkDdooRE8K6v2h

EXPLICAÇAO
"""

meu_dicionario = {}

aluno = {
'nome':'joao',
'idade':25,
'curso':'Ciencia',
}                                #Dicionario; os primeiros valores sao as chaves e os posteriores os valores referentes a cada chave

aluno['nota_final'] = 85        #Adiciona uma chave com um valor ao dicionario

for chave in aluno:            #Percorre pelas chaves do dicionario
  print(chave)

print('chave valor')           #Apresentar as chaves e valores do dicionario
for chave, valor in aluno.items():      #Adiciona 2 contadores ao FOR (Chave e valor) - .items retorna os valores de um dicionario
  print(chave, ':', valor)              # O [] chama as chaves do dicionario dentro do codigo: EX: [idade]

"""EXERCICIOS

1. Ler uma lista de 5 numeros inteiros e mostre cada numero juntamente com sua posiçao na lista
"""

lista = [1, 2, 3, 4, 5]
for i in lista:
  i +=0
for x in lista:
  x += 0

 print(i, x)

"""2. Ler uma lista de 10 numeros reais e mostre-os na orde inversa que foram lidos"""

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista.reverse()
print(lista)

"""3. Ler uma lista com 5 idades e exibir a maior e a menor"""

lista = [1, 2, 3, 4, 5]

print(f'''
Maximo: {max(lista)}
Minimo: {min(lista)}
''')

"""4. Inicialize uma lista de 10 numeros inteiros. Armazene os numeros pares em uma lista PAR e os numeros impares em uma lista IMPAR imprima as listas PAR e IMPAR"""

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista_par = [x for x in lista if x % 2 == 0]
lista_impar = [x for x in lista if x % 3 == 0]           #Arrumado pelo Colab (conferir)

print(f'''
Lista par: {lista_par}
Lista impar: {lista_impar}''')

"""5. Escreva um programa que troque o primeiro com o último
elemento de uma lista qualquer.
"""

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

lista[0], lista[-1] = lista[-1], lista[0]

print(lista)

"""6. Qual a saída/resultado da seguinte compreensão de lista?

Você consegue entender e explicar o resultado?
"""

[[1+ j*3 + i for i in range (3)] for j in range(3)]

"""7. Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.
produtos = {
'camiseta': (25.00, 10),
'calça': (45.00, 5),
'sapato': (60.00, 3),
'boné': (15.00, 8)
}
Você deve criar um programa em Python que solicite ao usuário que insira um preço
máximo. Em seguida, o programa deve imprimir os produtos cujo preço seja menor ou
igual ao preço máximo inserido pelo usuário.
"""

produtos = {'camiseta': (25.00, 10), 'calça': (45.00, 5), 'sapato': (60.00, 3), 'boné': (15.00, 8)}

menor_valor = []

preco = float(input("Digite o valor maximo que deseja que filtremos os produtos: "))

for chave, valor in produtos.items():
  if valor[0] <= preco :
    menor_valor.append(chave)

print(menor_valor)

"""8. Em uma competição de ginástica, cada atleta recebe votos de
sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica
sendo a média dos votos restantes. Você deve fazer um programa
que receba o nome do ginasta e as notas dos sete jurados
alcançadas pelo atleta em sua apresentação e depois informe a sua
média, conforme a descrição acima informada (retirar o melhor e o
pior salto e depois calcular a média com as notas restantes). As
notas não são informadas em ordem crescente ou decrescente.
"""

nome = input("Insira o nome do atleta: ").title()
notas = [] # Cria uma lista vazia

for contador in range(1,8): # faz o loop.
  nota = float(input(f"Insira a {contador}ª nota do salto: ")) # Recebe as notas do atleta.
  notas.append(nota) # Adiciona a nota na lista NOTAS
notas.sort()  #Classifica em ordem crecente a lista
notas.pop(0)  # .pop(0) remove o primeiro elemento da lista
notas.pop()   # .pop() remove o ultimo elemento da lista

# notas.remove(max(notas)) # Remove o valor Máximo da lista NOTAS
# notas.remove(min(notas)) # Remove o valor Minimo da lista NOTAS

media = sum(notas)/len(notas) # soma as notas e calcula a média.

print(f"O atleta {nome} teve uma média de {media:.2f} pontos.")